Repository silverstripe/silverstripe-admin, pull requests merged in 2018-04, with the labels that each got.

#471 NEW Add --inverted modifier for Badge component with pattern library examples
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Badge/Badge.js
  client/src/components/Badge/Badge.scss
  client/src/components/Badge/README.md
  client/src/components/Badge/mixins/_badge.scss
  client/src/components/Badge/tests/Badge-story.js
Labels: affects/v4, change/minor, type/enhancement

#479 MINOR Remove last of $this aliasing from admin module
  code/LeftAndMain.php
Labels: affects/v4, change/minor

#483 Add editorconfig rule for composer.json to be allowed four spaces
  .editorconfig
Labels: affects/v4, change/patch

#478 NEW Allow Preview fill-height to be removed and add i18n to messages
  client/dist/js/bundle.js
  client/src/components/Preview/Preview.js
  yarn.lock
Labels: affects/v4, change/minor

#488 MINOR: Modal response not covering modal properly
  client/dist/styles/bundle.css
  client/src/components/Modal/Modal.scss
Labels: affects/v4, change/patch

#487 FIX Ensure FormBuilder loading indicator has a minimum height of the image
  client/dist/styles/bundle.css
  client/src/containers/FormBuilderLoader/FormBuilderLoader.scss
Labels: affects/v4, change/patch

#490 NEW Add Loading indicator component, implement into FormBuilderLoader
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.js
  client/src/components/Loading/Loading.js
  client/src/components/Loading/README.md
  client/src/components/Loading/tests/Loading-story.js
  client/src/containers/FormBuilderLoader/FormBuilderLoader.js
  client/src/containers/FormBuilderLoader/FormBuilderLoader.scss
  client/src/styles/bundle.scss
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#503 FIX Expose Badge in injector registrations
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/src/boot/registerComponents.js
Labels: affects/v4, change/patch
