Repository silverstripe/silverstripe-admin, pull requests merged in 2018-03, with the labels that each got.

#453 BUG Fix page icons
  client/dist/styles/bundle.css
  client/src/styles/legacy/_style.scss
  client/src/styles/legacy/_tree.scss
Labels: affects/v4, change/patch

#456 Fix aligns Form actions container with the rest of the "bottom bars"
  client/dist/styles/bundle.css
  client/src/components/Form/Form.scss
Labels: affects/v4, impact/low, type/UX

#458 BUG Ensure lang is detected from html tag
  client/dist/js/bundle.js
  client/dist/js/i18n.js
  client/src/i18n.js
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug, type/frontend

#459 Fix "container" logic for FormBuilder and PopoverField, improves accessibility
  client/dist/js/bundle.js
  client/src/components/FormBuilder/FormBuilder.js
  client/src/components/PopoverField/PopoverField.js
Labels: affects/v4, impact/high, type/UX, type/bug

#460 Enhancement use scss variable than hard-coded color
  client/dist/styles/bundle.css
  client/src/components/UsedOnTable/UsedOnTable.scss
  yarn.lock
Labels: affects/v4, impact/low, type/UX, type/bug

#461 NEW Update table border colour and allow badge-pill to be overridden in Badge
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Badge/Badge.js
  client/src/styles/_bootstrap-variables.scss
Labels: affects/v4, change/minor, type/UX
