Repository silverstripe/silverstripe-admin, pull requests merged in 2018-06, with the labels that each got.

#536 Rename "Filter" label to "Search"
  lang/en.yml
  templates/SilverStripe/Admin/Includes/ModelAdmin_Content.ss
  templates/SilverStripe/Admin/Includes/ModelAdmin_Tools.ss
Labels: affects/v4, change/minor

#539 BUG Fix invalid .upgrade.yml
  .upgrade.yml
Labels: affects/v4, change/patch

#541 FIX Update user help link to 4
  code/LeftAndMain.php
Labels: affects/v4, change/patch, impact/low, type/docs, type/userhelp

#546 Fix display of GridField link existing button
  client/dist/styles/bundle.css
  client/src/styles/legacy/GridField.scss
  client/src/styles/legacy/_forms.scss
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/frontend

#550 FIX - Grid field headers misaligned
  client/dist/styles/bundle.css
  client/src/styles/legacy/GridField.scss
Labels: affects/v4, change/major, effort/easy, impact/low, type/bug, type/frontend
