Repository silverstripe/silverstripe-admin, pull requests merged in 2018-07, with the labels that each got.

#565 NEW Update PopoverField styles to match DSM designs
  client/dist/styles/bundle.css
  client/src/components/PopoverField/PopoverField.scss
  client/src/components/PopoverField/tests/PopoverField-story.js
  client/src/styles/_bootstrap-variables.scss
Labels: affects/v4, change/minor, type/frontend

#534 Add missing title attribute to profile link
  lang/en.yml
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuStatus.ss
Labels: affects/v4, effort/easy, impact/medium, type/UX, type/frontend

#563 Update fonts from Fontastic
  client/dist/fonts/silverstripe.eot
  client/dist/fonts/silverstripe.svg
  client/dist/fonts/silverstripe.ttf
  client/dist/fonts/silverstripe.woff
  client/dist/styles/bundle.css
  client/src/font/fonts/silverstripe.eot
  client/src/font/fonts/silverstripe.svg
  client/src/font/fonts/silverstripe.ttf
  client/src/font/fonts/silverstripe.woff
  client/src/font/icons-reference.html
  client/src/font/styles.css
  client/src/styles/_fonts.scss
Labels: affects/v4, change/minor

#564 NEW Add button class names and toggle callback to PopoverField component
  client/dist/js/bundle.js
  client/src/components/PopoverField/PopoverField.js
  client/src/components/PopoverField/README.md
  client/src/components/PopoverField/tests/PopoverField-story.js
Labels: affects/v4, change/minor

#545 Allow overflow-x on scrollable panels
  client/dist/styles/bundle.css
  client/src/styles/_layout.scss
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/UX, type/bug, type/frontend

#560 NEW Add ViewModeToggle component
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/boot/registerReducers.js
  client/src/bundles/bundle.js
  client/src/components/Preview/Preview.js
  client/src/components/Preview/Preview.scss
  client/src/components/ViewModeToggle/ViewModeToggle.js
  client/src/components/ViewModeToggle/ViewModeToggle.scss
  client/src/components/ViewModeToggle/tests/ViewModeToggle-test.js
  client/src/lib/constants.js
  client/src/state/viewMode/viewModeActionTypes.js
  client/src/state/viewMode/viewModeActions.js
  client/src/state/viewMode/viewModeReducer.js
  client/src/styles/bundle.scss
  package.json
  yarn.lock
Labels: affects/v4, change/minor, impact/medium, type/enhancement, type/frontend

#581 FIX #579 BUG Ambiguous column RecordID when doing batch actions
  code/CMSBatchActionHandler.php
Labels: affects/v4, change/patch
