Repository silverstripe/silverstripe-admin, pull requests merged in 2018-10, with the labels that each got.

#664 FIX Avoid having search fields with the same name as form elements
  client/dist/js/bundle.js
  client/src/components/Search/Search.js
  client/src/components/Search/SearchBox.js
  client/src/components/Search/SearchForm.js
  tests/behat/features/manage-users.feature
Labels: affects/v4, change/patch

#667 FIX Searching now allows + symbols, use own method over jQuery serialisation
  client/dist/js/bundle.js
  client/src/legacy/LeftAndMain.js
  client/src/legacy/sspath.js
Labels: affects/v4, change/patch

#671 FIX Quote injector alias references, deprecated and removed support for in Symfony 4
  _config/injector.yml
  _config/routes.yml
Labels: affects/v4, change/patch, impact/low

#416 NEW Add new tests for Form and CompositeField
  client/dist/js/bundle.js
  client/src/components/CompositeField/CompositeField.js
  client/src/components/CompositeField/tests/CompositeField-test.js
  client/src/components/Form/Form.js
  client/src/components/Form/tests/Form-test.js
Labels: affects/v4

#615 NEW Add CMS community help menu to cms-menu
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Menu/Menu.scss
  client/src/components/MobileMenuToggle/MobileMenuToggle.scss
  client/src/legacy/LeftAndMain.Menu.js
  client/src/styles/_variables.scss
  client/src/styles/legacy/_style.scss
  code/LeftAndMain.php
  lang/en.yml
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuLogo.ss
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
  tests/php/LeftAndMainTest.php
Labels: affects/v4, impact/medium, type/UX, type/enhancement, type/frontend, type/userhelp

#677 FIX Add fix for potential tabnabbing on community help links
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
Labels: affects/v4, change/patch

#676 FIX Ensure TinyMCE field changes are persisted before updating redux state
  client/dist/js/bundle.js
  client/src/components/HtmlEditorField/HtmlEditorField.js
Labels: affects/v4, change/patch

#669 NEW Tabs now store the active tab in redux state
  client/dist/js/bundle.js
  client/src/components/Tabs/Tabs.js
  client/src/containers/FormBuilderLoader/FormBuilderLoader.js
Labels: affects/v4, change/minor

#680 BUG ModelAdmin pagination with a filter
  code/ModelAdmin.php
Labels: affects/v4, change/patch

#678 MINOR Upgrade Bootstrap to 4.1.2
  client/dist/styles/bundle.css
  client/src/styles/_bootstrap-override.scss
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#681 FIX Only hide overflow from inactive chosen fields
  client/dist/styles/bundle.css
  client/src/styles/_chosen.scss
Labels: affects/v4, change/patch

#679 Implement logic to lazy load GridField in the frontend
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/legacy/GridField.js
  client/src/legacy/LeftAndMain.js
  client/src/legacy/TabSet.js
  client/src/styles/legacy/GridField.scss
Labels: affects/v4, change/minor

#683 ENHANCEMENT: Add nested fields, args, distribute args to fields
  client/dist/js/bundle.js
  client/src/lib/dependency-injection/ApolloGraphqlManager.js
  client/src/lib/dependency-injection/graphql/buildReadQuery.js
  client/src/lib/dependency-injection/graphql/helpers.js
  client/src/lib/dependency-injection/tests/ApolloGraphqlManager-test.js
  client/src/lib/dependency-injection/tests/ApolloGraphqlScaffoldingContainer-test.js
Labels: affects/v4, change/minor

#690 Tidy up menu toggle buttons
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Menu/Menu.scss
  client/src/images/sticky-toggle-off.png
  client/src/images/sticky-toggle-on.png
  client/src/legacy/LeftAndMain.Menu.js
  client/src/styles/legacy/_style.scss
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
Labels: affects/v4, change/patch

#688 Fix long gridfield actions overflowing
  client/dist/styles/bundle.css
  client/src/components/GridFieldActions/GridFieldActions.scss
Labels: affects/v4, change/patch

#697 Fix body overflow causing scroll bars
  client/dist/styles/bundle.css
  client/src/components/Menu/Menu.scss
  client/src/styles/legacy/_style.scss
  templates/SilverStripe/Admin/Includes/LeftAndMain_Menu.ss
Labels: affects/v4, change/patch

#694 BUGFIX: Move tab state to redux store instead of reduxForm
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/src/boot/registerReducers.js
  client/src/components/Tabs/Tabs.js
  client/src/components/Tabs/tests/Tabs-test.js
  client/src/state/tabs/TabsActionTypes.js
  client/src/state/tabs/TabsActions.js
  client/src/state/tabs/TabsReducer.js
Labels: affects/v4, change/patch

#695 BUG: Fixes #674 TinyMCE width
  client/dist/styles/bundle.css
  client/src/components/Form/Form.scss
Labels: affects/v4, change/patch

#698 ENHANCEMENT: Reverse argument signature of methods using path
  client/dist/js/bundle.js
  client/src/lib/dependency-injection/ApolloGraphqlManager.js
  client/src/lib/dependency-injection/tests/ApolloGraphqlManager-test.js
  client/src/lib/dependency-injection/tests/ApolloGraphqlScaffoldingContainer-test.js
Labels: affects/v4, change/major

#701 FIX Change one tab not all tabs
  client/dist/js/bundle.js
  client/src/bundles/bundle.js
  client/src/components/Tabs/Tabs.js
Labels: affects/v4, change/patch

#705 FIX Remove deprecated help_link definition in testGetHelpLinks
  tests/php/LeftAndMainTest.php
Labels: affects/v4, change/patch

#691 BUG Don’t track gridstate changes as form edits
  client/dist/js/vendor.js
  thirdparty/jquery-changetracker/lib/jquery.changetracker.js
Labels: affects/v4, change/patch

#707 Add PHP 7.2 and 7.3 to Travis matrix
  .travis.yml
Labels: affects/v4, change/patch

#693 Convert some existing stories to use the JSX module
  client/dist/js/bundle.js
  client/src/components/Badge/Badge.js
  client/src/components/Badge/tests/Badge-story.js
  client/src/components/Breadcrumb/tests/Breadcrumb-story.js
  client/src/components/CheckboxField/CheckboxField.js
  client/src/components/CheckboxField/tests/CheckboxField-story.js
  client/src/components/CheckboxSetField/CheckboxSetField.js
  client/src/components/CheckboxSetField/tests/CheckboxSetField-story.js
  client/src/components/Tag/tests/Tag-story.js
Labels: affects/v4, change/minor, effort/easy, impact/low, type/enhancement

#684 NEW Adding a component for a generic popover filled with buttons
  .storybook/addons.js
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/PopoverOptionSet/PopoverOptionSet.js
  client/src/components/PopoverOptionSet/PopoverOptionSet.scss
  client/src/components/PopoverOptionSet/PopoverOptionSetToggle.js
  client/src/components/PopoverOptionSet/README.md
  client/src/components/PopoverOptionSet/tests/PopoverOptionSet-story.js
  client/src/components/PopoverOptionSet/tests/PopoverOptionSet-test.js
  client/src/styles/bundle.scss
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#687 Fix search filtering and clearing
  client/dist/js/bundle.js
  client/src/components/Search/README.md
  client/src/components/Search/Search.js
  client/src/components/Search/tests/Search-test.js
  client/src/components/Tag/Tag.js
  client/src/components/Tag/tests/Tag-test.js
  client/src/components/Tag/tests/TagList-test.js
  client/src/containers/FormBuilderLoader/FormBuilderLoader.js
  client/src/legacy/GridField.js
  client/src/legacy/LeftAndMain.js
Labels: affects/v4, change/patch

#712 FIX Replace usage of Convert JSON methods with json_encode and json_decode
  code/CMSBatchAction.php
  code/LeftAndMain.php
Labels: affects/v4, change/minor

#718 FIX Add aria-expanded to help menu toggle for screenreader accessibility
  client/dist/js/bundle.js
  client/src/legacy/LeftAndMain.Menu.js
  templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
Labels: affects/v4, change/patch, impact/low, type/UX, type/bug
