Repository silverstripe/silverstripe-admin, pull requests merged in 2018-05, with the labels that each got.

#501 ENHANCEMENT Ensure that popover has correct container assigned
  client/dist/images/spinner.gif
  client/dist/images/sprite-btn-icon.png
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/FormBuilder/FormBuilder.js
  client/src/components/PopoverField/PopoverField.js
  client/src/components/PopoverField/PopoverField.scss
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/enhancement, type/frontend

#511 ENHANCEMENT Register fieldHolder HOCs with injector
  client/dist/js/bundle.js
  client/src/boot/applyTransforms.js
  client/src/components/FieldGroup/FieldGroup.js
Labels: affects/v4, change/minor

#505 NEW Make Preview component injectable
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/src/boot/registerComponents.js
Labels: affects/v4, change/minor

#519 FIX Coerce textfield value attributes to empty strings
  client/dist/js/bundle.js
  client/src/components/FormBuilder/FormBuilder.js
  client/src/components/SingleSelectField/SingleSelectField.js
  client/src/components/TextField/TextField.js
Labels: affects/v4, change/patch

#485 FIX Make 'id' a required prop
  client/dist/js/bundle.js
  client/src/components/PopoverField/PopoverField.js
Labels: affects/v4, change/minor

#525 NEW Make FormAlert injectable
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
Labels: affects/v4, change/minor
