Repository silverstripe/silverstripe-admin, pull requests merged in 2018-11, with the labels that each got.

#582 ENH Improve loading screen and indicator
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Loading/Loading.js
  client/src/legacy/LeftAndMain.js
  client/src/styles/legacy/_retina.scss
  client/src/styles/legacy/_style.scss
  templates/SilverStripe/Admin/Includes/CMSLoadingScreen.ss
Labels: affects/v4, change/minor

#719 FIX Remove incorrect modal close icon hover colour
  client/dist/styles/bundle.css
  client/src/components/Modal/Modal.scss
Labels: affects/v4, impact/low, type/UX, type/bug, type/frontend

#720 FIX Update gridfield sorted icon and border colours
  client/dist/styles/bundle.css
  client/src/components/GridField/GridField.scss
Labels: affects/v4, impact/low, type/UX, type/bug

#748 MINOR Move @storybook/addon-knobs to devDependencies
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  package.json
Labels: affects/v4, change/minor

#643 NEW Use Bootstrap alerts throughout the CMS
  _config/forms.yml
  code/Forms/FormMessageBootstrapAdapter.php
  templates/SilverStripe/Admin/Includes/CMSProfileController_EditForm.ss
  templates/SilverStripe/Admin/Includes/LeftAndMain_EditForm.ss
  themes/cms-forms/templates/RightLabelledFieldHolder.ss
  themes/cms-forms/templates/SilverStripe/Forms/CheckboxField_holder.ss
  themes/cms-forms/templates/SilverStripe/Forms/CompositeField_holder.ss
  themes/cms-forms/templates/SilverStripe/Forms/DatetimeField_holder.ss
  themes/cms-forms/templates/SilverStripe/Forms/FieldGroup_holder.ss
  themes/cms-forms/templates/SilverStripe/Forms/FormField_holder.ss
  themes/cms-forms/templates/SilverStripe/Forms/Includes/Form.ss
  themes/cms-forms/templates/SilverStripe/Forms/OptionsetField_holder.ss
Labels: affects/v4, change/minor

#661 NEW Add update extension hooks for LinkFormFactory subclasses
  code/Forms/EditorEmailLinkFormFactory.php
  code/Forms/LinkFormFactory.php
Labels: affects/v4, change/minor

#754 MINOR Change Tag class to avoid conflict with taxanomie
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Tag/Tag.js
  client/src/components/Tag/Tag.scss
  client/src/components/Tag/tests/Tag-test.js
  client/src/components/Tag/tests/TagList-test.js
  yarn.lock
Labels: affects/v4, change/minor

#756 FIX Correct the entwine match for the loading animation
  client/dist/js/bundle.js
  client/src/legacy/LeftAndMain.js
Labels: affects/v4, change/patch

#762 FIX Ensure TinyMCE is correctly instantiated and removed when dom matching changes
  client/dist/js/bundle.js
  client/src/components/PopoverOptionSet/tests/PopoverOptionSet-test.js
  client/src/legacy/HtmlEditorField.js
Labels: affects/v4, change/patch

#760 FIX Readding ARCHIVECONFIRMMESSAGE
  client/lang/src/en.json
Labels: affects/v4, change/patch
