Repository silverstripe/silverstripe-admin, pull requests merged in 2018-08, with the labels that each got.

#589 FIX ViewModeToggle now uses BEM class naming convention
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/Preview/Preview.scss
  client/src/components/ViewModeToggle/ViewModeToggle.js
  client/src/components/ViewModeToggle/ViewModeToggle.scss
  client/src/components/ViewModeToggle/tests/ViewModeToggle-test.js
Labels: affects/v4, change/patch

#506 MINOR Clarify that closeLabel will make alerts dismissible, fix story book example
  client/src/components/FormAlert/README.md
  client/src/components/FormAlert/tests/FormAlert-story.js
Labels: affects/v4, change/minor

#557 NEW Pattern library now has FormAction examples
  client/src/components/FormAction/README.md
  client/src/components/FormAction/tests/FormAction-story.js
Labels: affects/v4, change/minor, impact/low

#592 NEW ViewModeToggle states are now stored in constants
  client/dist/js/bundle.js
  client/src/bundles/bundle.js
  client/src/components/ViewModeToggle/ViewModeToggle.js
  client/src/state/viewMode/ViewModeReducer.js
  client/src/state/viewMode/ViewModeStates.js
Labels: affects/v4, change/minor

#604 FIX side scroll overflow of cms-preview
  client/dist/styles/bundle.css
  client/src/styles/_chosen.scss
Labels: affects/v4, change/patch

#603 FIX text/json is not a mimetype
  client/dist/js/bundle.js
  client/src/legacy/LeftAndMain.js
  client/src/state/records/RecordsActions.js
Labels: affects/v4, change/patch

#610 ENH Add dropdownToggleClassNames prop and toggleCallback to ActionMenu
  client/dist/js/bundle.js
  client/src/components/ActionMenu/ActionMenu.js
Labels: affects/v4, change/minor

#516 FIX: Add missing focus styles for preview options (fixes silverstripe/silverstripe-framework #2101)
  client/dist/styles/bundle.css
  client/src/styles/legacy/_preview.scss
Labels: affects/v4, change/patch

#618 Fix Add mock store to the loadComponent ApolloProvider
  client/src/lib/dependency-injection/tests/loadComponent-test.js
Labels: affects/v4, change/patch

#613 FIX Site tree items do not disappear on save with source file comments enabled
  client/dist/js/bundle.js
  client/src/legacy/LeftAndMain.Tree.js
Labels: affects/v4, change/patch
