Repository silverstripe/silverstripe-admin, pull requests merged in 2018-09, with the labels that each got.

#630 Revisions to datefield to have better HTML5 fallbacks
  client/dist/js/bundle.js
  client/src/components/DateField/DateField.js
  client/src/components/DateField/tests/DateField-test.js
Labels: affects/v4, change/patch

#634 FIX Remove action menu toggle styles
  client/dist/styles/bundle.css
  client/src/styles/legacy/GridField.scss
Labels: affects/v4, change/minor, type/UX, type/frontend

#628 NEW HtmlEditorField component for react rich text
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/src/boot/registerComponents.js
  client/src/components/Form/Form.js
  client/src/components/FormBuilder/FormBuilder.js
  client/src/components/HtmlEditorField/HtmlEditorField.js
  client/src/legacy/HtmlEditorField.js
  package.json
  yarn.lock
Labels: affects/v4, change/minor, impact/high

#638 Make section name in Client Config configurable.
  code/LeftAndMain.php
Labels: affects/v4, change/patch

#647 NEW Add hideNav flag to allow hiding of navigation in Tabs
  client/dist/js/bundle.js
  client/src/components/Tabs/Tabs.js
  client/src/components/Tabs/tests/Tabs-test.js
Labels: affects/v4, change/minor

#654 NEW Form state & schema persists across form remounting
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/src/components/HtmlEditorField/HtmlEditorField.js
  client/src/containers/Form/Form.js
  client/src/containers/FormBuilderLoader/FormBuilderLoader.js
  package.json
  yarn.lock
Labels: affects/v4, change/minor
