Repository silverstripe/silverstripe-admin, pull requests merged in 2019-01, with the labels that each got.

#767 FIX "Clear" button in PopoverOptionSet search now has no right margin
  client/dist/styles/bundle.css
  client/src/components/PopoverOptionSet/PopoverOptionSet.scss
Labels: affects/v4, change/patch

#766 FIX PopoverOptionSet now explicitly sets an auto height for its search field
  client/dist/js/vendor.js
  client/dist/styles/bundle.css
  client/src/components/PopoverOptionSet/PopoverOptionSet.scss
Labels: affects/v4, change/patch

#789 Fix behat reauthenticate tests
  .travis.yml
  tests/behat/features/reauthenticate.feature
Labels: affects/v4, change/patch

#801 FIX Forwarding action state in another situation where it was not being forwarded
  client/dist/js/bundle.js
  client/src/components/GridFieldActions/GridFieldActions.js
Labels: affects/v4, change/patch

#803 NEW Add font-icon support for site tree
  client/dist/fonts/silverstripe.eot
  client/dist/fonts/silverstripe.svg
  client/dist/fonts/silverstripe.ttf
  client/dist/fonts/silverstripe.woff
  client/dist/styles/bundle.css
  client/src/font/fonts/silverstripe.eot
  client/src/font/fonts/silverstripe.svg
  client/src/font/fonts/silverstripe.ttf
  client/src/font/fonts/silverstripe.woff
  client/src/font/icons-reference.html
  client/src/font/styles.css
  client/src/styles/_fonts.scss
  client/src/styles/legacy/_style.scss
  client/src/styles/legacy/_tree.scss
Labels: affects/v4, change/minor

#806 FIX: Use lighter colour for placeholders (fixes #805)
  client/dist/styles/bundle.css
  client/src/styles/_bootstrap-override.scss
  client/src/styles/_bootstrap-variables.scss
Labels: affects/v4, change/patch, type/UX

#641 FIX ActionsMenu does not pass toggleCallback prop to Dropdown
  client/dist/js/bundle.js
  client/src/components/ActionMenu/ActionMenu.js
Labels: affects/v4, change/patch
