Repository silverstripe/silverstripe-admin, pull requests merged in 2020-10, with the labels that each got.

#1123 ENH Replace E_USER_ERROR errors with exceptions
  code/ModelAdmin.php
Labels: affects/v4, change/minor

#1128 FIX React components for reactstrap 8 upgrade
  behat.yml
  client/dist/js/bundle.js
  client/src/components/Accordion/tests/Accordion-test.js
  client/src/components/Accordion/tests/AccordionBlock-test.js
  client/src/components/FieldGroup/tests/FieldGroup-test.js
  client/src/components/Focusedzone/tests/Focusedzone-test.js
  client/src/components/HeaderField/tests/HeaderField-story.js
  client/src/components/HiddenField/HiddenField.js
  client/src/components/HiddenField/tests/HiddenField-story.js
  client/src/components/HiddenField/tests/HiddenField-test.js
  client/src/components/HtmlEditorField/tests/HtmlEditorField-test.js
  client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
  client/src/components/HtmlReadonlyField/tests/HtmlReadonlyField-story.js
  client/src/components/InputField/tests/InputField-test.js
  client/src/components/LabelField/tests/LabelField-test.js
  client/src/components/LiteralField/tests/LiteralField-story.js
  client/src/components/LiteralField/tests/LiteralField-test.js
  client/src/components/LookupField/LookupField.js
  client/src/components/MobileMenuToggle/tests/MobileMenuToggle-test.js
  client/src/components/NotFoundComponent/tests/NotFoundComponent-test.js
  client/src/components/Preview/tests/Preview-test.js
  client/src/components/ResizeAware/tests/ResizeAware-test.js
  client/src/components/SingleSelectField/SingleSelectField.js
  client/src/components/SingleSelectField/tests/SingleSelectField-test.js
  client/src/components/Tabs/tests/Tabs-story.js
  client/src/components/Toolbar/tests/Toolbar-story.js
  client/src/components/Toolbar/tests/Toolbar-test.js
Labels: affects/v4, change/minor, effort/easy, impact/high, type/bug

#1134 Update react from 16.11 > 16.13
  client/dist/js/vendor.js
  yarn.lock
Labels: affects/v4, change/minor

#1141 FIX Patch Entwine to ignore missing methods in one()
  client/dist/js/vendor.js
  thirdparty/jquery-entwine/dist/jquery.entwine-dist.js
  thirdparty/jquery-entwine/src/jquery.entwine.js
Labels: affects/v4, change/patch, effort/medium, impact/critical, type/bug

#1142 FIX Adjust search form widths to prevent date cutoff
  client/dist/styles/bundle.css
  client/src/components/Search/SearchForm.scss
  client/src/styles/legacy/_style.scss
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX
