Repository silverstripe/silverstripe-admin, pull requests merged in 2020-03, with the labels that each got.

#1021 FIX Switch incorrect modified and draft state indicator colours
  client/dist/styles/bundle.css
  client/src/styles/_variables.scss
Labels: affects/v4, change/patch, impact/high, type/UX, type/bug

#1022 FIX "My profile" title in CMS is now vertical centered as other LeftAndMain screens are
  templates/SilverStripe/Admin/Includes/CMSProfileController_Content.ss
Labels: affects/v4, change/patch

#1023 Upgrade to phpunit 8
  composer.json
  tests/php/LeftAndMainTest.php
Labels: affects/v5
