Repository silverstripe/silverstripe-admin, pull requests merged in 2020-09, with the labels that each got.

#1101 FIX: Fix ModelAdmin slug flex when getManagedModels() is overridden.
  code/ModelAdmin.php
Labels: affects/v4, change/minor, effort/easy, impact/high, type/bug

#1068 Reimplement toast in React so we can use them everywhere
  client/dist/js/LeftAndMain.Ping.js
  client/dist/js/MemberImportForm.js
  client/dist/js/bundle.js
  client/dist/js/vendor.js
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/boot/registerComponents.js
  client/src/boot/registerReducers.js
  client/src/bundles/bundle.js
  client/src/bundles/vendor.js
  client/src/components/LookupField/tests/LookupField-test.js
  client/src/components/Tabs/TabItem.js
  client/src/components/Tag/tests/Tag-test.js
  client/src/components/Toasts/README.md
  client/src/components/Toasts/Toast.js
  client/src/components/Toasts/ToastActions.js
  client/src/components/Toasts/Toasts.js
  client/src/components/Toasts/Toasts.scss
  client/src/components/Toasts/tests/Toast-test.js
  client/src/components/Toasts/tests/ToastActions-test.js
  client/src/components/Toasts/tests/Toasts-story.js
  client/src/components/Toasts/tests/Toasts-test.js
  client/src/containers/ToastsContainer/ToastsContainer.js
  client/src/legacy/LeftAndMain.BatchActions.js
  client/src/legacy/LeftAndMain.js
  client/src/legacy/ToastsContainer.js
  client/src/state/toasts/ToastConstants.js
  client/src/state/toasts/ToastsActionTypes.js
  client/src/state/toasts/ToastsActions.js
  client/src/state/toasts/ToastsReducer.js
  client/src/state/toasts/ToastsTypes.js
  client/src/state/toasts/tests/ToastsReducer-test.js
  client/src/styles/_variables.scss
  client/src/styles/bundle.scss
  package.json
  tests/behat/features/profile.feature
  thirdparty/jquery-notice/.piston.yml
  thirdparty/jquery-notice/jquery.notice.css
  thirdparty/jquery-notice/jquery.notice.js
  yarn.lock
Labels: affects/v4, change/minor, effort/hard, impact/medium, type/enhancement

#1111 NEW Show icons on tabs with invalid form field values
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/legacy/LeftAndMain.EditForm.js
  client/src/styles/legacy/_style.scss
Labels: affects/v4, change/patch, effort/easy, impact/high, type/enhancement
